### ISSUE TITLE
Can't Delete Backups

### ISSUE THREAD

**Issue by Jkryv3nchuk** [ComputerElite/QuestAppVersionSwitcher#1]
Platform: Oculus/Meta Quest 2
Game: Beat Saber

Hello, I was trying to use the "Delete Backup" button but it does not seem to actually delete the Backup. I made sure to update to the latest release posted and that still did not fix the issue.

Thanks so much for making this App, it's made it very easy to switch between Vanilla and Modded Beat Saber!

**Comment by ComputerElite** [comment]
Hi, 
The delete backup button should be working. Have you tried restarting your quest and QuestAppVersionSwitcher?

**Comment by ComputerElite** [comment]
And does it give any error back to you or just say "Succesfully deleted"?

**Comment by Jkryv3nchuk** [comment]
I have restarted my Quest a couple times and it does not give an error or anything when I press the button.

**Comment by ComputerElite** [comment]
That is weird. I'll investigate and keep you informed

**Comment by Jkryv3nchuk** [comment]
Thank you!

**Comment by ComputerElite** [comment]
download the newest version from the releases tab. I fixed the issue and will update the sidequest listing tomorrow. Thanks for reporting. If there are any more problems feel free to create a new issue

**Comment by Jkryv3nchuk** [comment]
Thank you so much!
