### ISSUE TITLE
Can't  put a password

### ISSUE THREAD

**Issue by TheCyberGalaxy** [ComputerElite/QuestAppVersionSwitcher#10]
I have had the problem that I can't put a password for the token. When I try to do it it just freezes and doesn't do anything else.
Can you help me fix this issue?
![Bild_2022-10-09_205406173](https://user-images.githubusercontent.com/57366708/194774504-f6c2bc6b-875e-4589-be91-1894695a825f.png)

**Comment by ComputerElite** [comment]
Have you tried to restart your quest yet?

**Comment by TheCyberGalaxy** [comment]
No... I-
Found the problem..
It was the wrong token xD
I was on the wrong website. So I pasted in a token of a "application"

**Comment by ComputerElite** [comment]
that explains, have a great day then

**Comment by ComputerElite** [comment]
The issue has been fixed in version 1.6.2 https://github.com/ComputerElite/QuestAppVersionSwitcher/releases/tag/1.6.2
