### ISSUE TITLE
can you solve this

### ISSUE THREAD

**Issue by iamcurrentlyhittingthegriddy** [ComputerElite/QuestAppVersionSwitcher#11]
when i was trying to downgrade a game known as capuchin, i tried to download the oldest version and somehow it gave me an unknown error. i already entered my token and somehow doesn't work

**Comment by ComputerElite** [comment]
1. Do you own the game?
2. Does the download buttons say `Download` or `Download (developer only)`

**Comment by DawnXofXFear** [comment]
have the same issue

**Comment by DawnXofXFear** [comment]
im logged in trough the website (not token)
