### ISSUE TITLE
Game won’t reinstall 

### ISSUE THREAD

**Issue by Beansticks** [ComputerElite/QuestAppVersionSwitcher#12]
Everything is working great up until the point where you had to reinstall the game with the older version. The game I’m trying to downgrade is called gorilla tag And it won’t reinstall. When I try to do this, it keeps switching between stage two and stage 2.1 Could you please help me try to fix this?

**Comment by ComputerElite** [comment]
Disable app sharing and remove all other accounts from your quest

**Comment by Beansticks** [comment]
Thx
