### ISSUE TITLE
Mods are glitched and wont delete

### ISSUE THREAD

**Issue by DawnXofXFear** [ComputerElite/QuestAppVersionSwitcher#13]
idk what happened but some of my mods refuse to deleta now

**Comment by ComputerElite** [comment]
Please press the upload mods button in the tools and options tab after trying to delete mods and tell me the id

**Comment by DawnXofXFear** [comment]
84D469

**Comment by DawnXofXFear** [comment]
i mainly use QAVS Mos Manager because of gliched PlayDataKeeper.
Wich only affects 1.25.1

**Comment by ComputerElite** [comment]
That log does not show any issues with mod deletion. Perhaps it works again?

**Comment by DawnXofXFear** [comment]
Nope still have the same Error as before.
Gonna send a Video in a Minute.

**Comment by DawnXofXFear** [comment]
I deleted everything that said mod and it fixed
