### ISSUE TITLE
Add option to assign different port

### ISSUE THREAD

**Issue by ryan77627** [ComputerElite/QuestAppVersionSwitcher#2]
Hello! I ran into a weird issue with BMBF (for beat saber) acting really weird whenever I change versions. Turn out it uses port 50001 for its websocket connection, which is what this app uses as well.

I was wondering if it would be possible to either add an option to change the port in the interface or add a button to kill the app, since it has a tendency to run in the background of my quest (even when I close it in the headset)

Thanks!

**Comment by ComputerElite** [comment]
Oh thought BMBF uses port 50000 as well for it's websocket connection. I'll add an option to both chabge the port and kill the app. Thanks!

**Comment by ComputerElite** [comment]
Version 1.2 added what you requested. Feel free to report further issues.
