### ISSUE TITLE
blade and sorcery downgrade

### ISSUE THREAD

**Issue by DAVISISHERE** [ComputerElite/QuestAppVersionSwitcher#21]
when im downloading the downgrade it gets stuck at 6.03% and 42/697

**Comment by ComputerElite** [comment]
I'm already working on a fix for that. If you want you can try the latest apk. That may or may not fix the issue https://drive.google.com/file/d/1Tc7rLStpO8LwWgCuKQzFMV-XfLj1uXWA/view?usp=share_link

**Comment by DAVISISHERE** [comment]
thank you!
