### ISSUE TITLE
Stuck on new update screen

### ISSUE THREAD

**Issue by AJBoyStylez** [ComputerElite/QuestAppVersionSwitcher#22]
I am stuck on the new update screen how do i get off it

**Comment by Hj082608** [comment]
Me too

**Comment by ComputerElite** [comment]
You press update now?

**Comment by Hj082608** [comment]
There's no option to it shows part of the screen but I can't scroll bc it
don't show the full thing

**Comment by ComputerElite** [comment]
Restart your quest, just pushed another update

**Comment by Hj082608** [comment]
Awesome, thanks!
