### ISSUE TITLE
No redirection after logging in

### ISSUE THREAD

**Issue by AJBoyStylez** [ComputerElite/QuestAppVersionSwitcher#23]
After I logged into my oculus account it didnt redirect me back to the quest app switcher page what do i do

**Comment by ComputerElite** [comment]
With which account did you log in? meta, facebook, instagram?

**Comment by joebobbio** [comment]
Works on my machine(tm) logging in with meta account

**Comment by ComputerElite** [comment]
The issue has now been completely fixed. There should no longer be any issues logging in. Thanks to @AltyFox
