### ISSUE TITLE
login problem

### ISSUE THREAD

**Issue by zwlekanie** [ComputerElite/QuestAppVersionSwitcher#26]
when i try to login there will be a popup saying that an error has occured
:c

**Comment by ComputerElite** [comment]
Do you have a pc?

**Comment by zwlekanie** [comment]
> 

yes

**Comment by ComputerElite** [comment]
Could you join this discord server and help me debug the problem? https://discord.gg/Ke5BWQCh
Just ping me when you joined

**Comment by ComputerElite** [comment]
This issue has been fixed in a recent update
