### ISSUE TITLE
Backs not showing

### ISSUE THREAD

**Issue by julzihead** [ComputerElite/QuestAppVersionSwitcher#29]
None of my backups for beatsaber is showing- list is empty, even if I try creating one on the spot it will say backup created but not show on the list. I’ve tried reinstalling the app but same thing.

**Comment by ComputerElite** [comment]
Please press upload logs in the tools and options tab and tell me the id it spits you out

**Comment by julzihead** [comment]
I manually deleted the .beatgames backups folder and now it’s working
