### ISSUE TITLE
Version 1.2.0 Launch issue

### ISSUE THREAD

**Issue by ryan77627** [ComputerElite/QuestAppVersionSwitcher#3]
Hello again! I finally received my new Quest and was installing the newest version you released for me a few days ago, however I'm having trouble launching it. Version 1.1.6 will launch fine when installed. I am now on Quest 2 rather than Quest 1 as I was before.

Logcat gives this error regarding the app's crash message:

`No assemblies found in '/data/user/0/com.ComputerElite.questappversionswitcher/files/.__override__' or ''. Assuming this is part of Fast Deployment. Exiting...`

I can get a backtrace if need be.

Thanks!

**Comment by ComputerElite** [comment]
Oh I'll upload another version later today (in approximately 11 hours) and tell you about it.

**Comment by ryan77627** [comment]
No problem, thank you! I'll be a bit busy tomorrow myself but I'll try to install the new build before I go to bed to verify.

**Comment by ComputerElite** [comment]
Uploaded a new build. Feel free to try it: https://github.com/ComputerElite/QuestAppVersionSwitcher/releases/tag/1.2.1

**Comment by ryan77627** [comment]
New build launches perfectly, thanks!
