### ISSUE TITLE
Feature Request: Install APKs

### ISSUE THREAD

**Issue by iamsirsammy** [ComputerElite/QuestAppVersionSwitcher#32]
I think it would be nice if you could install normal 2d android APKs with this app. Currently you can use a third party file manager to install android APKs downloaded from the meta quest store, but there's no way to get that from Sidequest AFAIK so you have to sideload twice.
A file picker might be a bit complicated, so I think just have a button to install a good file manager like https://f-droid.org/en/packages/com.amaze.filemanager/ or https://f-droid.org/en/packages/me.zhanghai.android.files/ would be a good idea, maybe adding Aurora Store for google play apps later.
This might not really fit this project but it would be a useful feature that doesn't seem to be anywhere else. I'm willing to help with this, knowing how to code, but I haven't worked with android before so I don't know how useful I'll be.

**Comment by AltyFox** [comment]
Personally, I believe this is outside the scope of this project.
The name of this project specifically calls Quest app.

Sideloaded 2D apps is outside the scope of this project,
However, I would not be opposed to the idea of adding an install apk button, it would be generic enough to fit this project yet open enough to allow sideloading of 2D apps

**Comment by ComputerElite** [comment]
Iirc Alteran wanted to work on a PC app to upload apks to QAVS. The code for installing any apk already exists. We'd just need a button. It's easy enough to implement. I'll take a look at that when I got time

**Comment by AltyFox** [comment]
> Iirc Alteran wanted to work on a PC app to upload apks to QAVS. The code for installing any apk already exists. We'd just need a button. It's easy enough to implement. I'll take a look at that when I got time

Oh man, I completely forgot about this, when other stuff hit the fan.  Hehe

**Comment by FrozenAlex** [comment]
I can just receive apks in the new ui using drag and drop so it will be even more fun to do.

**Comment by ComputerElite** [comment]
Keep in mind that the install apk endpoint seperate is. Iirc I made it so it just makes a new "Backup". You'll still have to restore it manually

**Comment by FrozenAlex** [comment]
Btw why can't we install apks directly? We still need to confirm it on quest itself so it is probably not a security issue

**Comment by ComputerElite** [comment]
because of that? Like you can just automatically start a restore prompt when the apk uploaded. I think the backup name gets sent after it uploaded but I gotta check that first

**Comment by ComputerElite** [comment]
An install apk button has been added in the newest update (1.13.12). it's in the tools & options tab and opens a file picker where you can select the apk you want to install from your quest file system
