### ISSUE TITLE
Good app but

### ISSUE THREAD

**Issue by skrecek5** [ComputerElite/QuestAppVersionSwitcher#33]
Good app but the issue here is that the .apk does not appear in your downloads folder, it should be so it appears there cause i want to play a downgraded game with my friends.

**Comment by ComputerElite** [comment]
Apks don't appear on your downloads folder. They are in the backup tab after download

**Comment by skrecek5** [comment]
Oh okay but could you atleast make a option to make it appear in the download folder

**Comment by ComputerElite** [comment]
Nope, you can find the apk in the QuestAppVersionSwitcher folder

**Comment by skrecek5** [comment]
> Nope, you can find the apk in the QuestAppVersionSwitcher folder

oh okay thanks
