### ISSUE TITLE
Backup failed: access to path denied

### ISSUE THREAD

**Issue by sdmeijer** [ComputerElite/QuestAppVersionSwitcher#34]
I tried to backup an app (which I succesfully backupped a couple of months ago) and it failed with:
Backup failed: Access to the path '/storage/emulated/0/Android/data/[appname]' is denied.

How to resolve this?

**Comment by ComputerElite** [comment]
Could you provide your quest OS version?

**Comment by sdmeijer** [comment]
54.0.0.151.344.480997738

**Comment by ComputerElite** [comment]
Press request Android directory permission in the tools and options tab and allow access

**Comment by sdmeijer** [comment]
I don't have that option, but figured out the problem. I was still using version 1.8.1.0 (I didn't get any update prompts from SideQuest). I updated your app manually and now I can set these rights. The backup is now succesful.
