### ISSUE TITLE
Custom Sabers Dont work

### ISSUE THREAD

**Issue by SupremeMedo** [ComputerElite/QuestAppVersionSwitcher#35]
I have Downloaded Qavs since 2 weeks i havent found any issues into it but, now i want custom beat saber whackers i downloaded alot but nothing shows in the cosmetics tab i use cx file explorer, i looked over for tutorials but they are all for bmbf which is outdated and i dont like it,
i only stopped using bmbf because there is no backup for versions thats why i prefer qavs,
should i use other modders like: mod assistant for beat saber?

**Comment by ComputerElite** [comment]
How did you download the whackers?

**Comment by SupremeMedo** [comment]
I honestly dont know i told my friend to get me some whackers he gave me some of his own that work on his and they all ended in .whacker, does it have to do with the direction of the files?

**Comment by ComputerElite** [comment]
You somehow have to get them on your quest. How did you upload them to your quest?

**Comment by SupremeMedo** [comment]
I have them on my quest, i have sidequest and i sideloaded discord and from there i made my friend send me them over there as i told u and i just pressed the download button

**Comment by ComputerElite** [comment]
For them to show up in game you'll have to upload them using QAVS. To do that note down the link shown at the top of the Tools and options tab in QAVS. You can then open that in the Meta Quest Browser. From there you can go to the cosmetics tab, hit upload and select the whacker file you downloaded from discord

**Comment by SupremeMedo** [comment]
Ok ill try that and tell u, also! Will they appear if i create another backup?

**Comment by ComputerElite** [comment]
You do not have to create a backup to use whacker. However, yes, they will persist if you restore another backup

**Comment by SupremeMedo** [comment]
Ok thanks for helping it worked 🫶🏻
