### ISSUE TITLE
Won’t stop making me approve access to android folders

### ISSUE THREAD

**Issue by ThomasTay09** [ComputerElite/QuestAppVersionSwitcher#36]
Whenever I open the app after closing it, it forces me to approve access to the data and obb folders in android. Even when I’m trying to download mods it would randomly pop up after clicking the “quest app version switcher button” after installing the mods to beat saber. Every time I open it it immediately makes me approve it again. Please help, this is getting very annoying having to approve it every time.

**Comment by joebobbio** [comment]
If you're on v55 this is a known OS bug

**Comment by ThomasTay09** [comment]
> If you're on v55 this is a known OS bug

Okay yea I'm on v55

**Comment by ComputerElite** [comment]
Should be fixed in the newest version. At least it should only ask once on startup instead of a few times
