### ISSUE TITLE
saying that i do not have the game even if i have it

### ISSUE THREAD

**Issue by Rodrigo311908ga** [ComputerElite/QuestAppVersionSwitcher#37]
im trying to down grade gorilla tag but i says i do not

**Comment by ComputerElite** [comment]
If it says you do not have the game then you do not have the game. Log in with the correct meta account on which you bought the game

**Comment by Rodrigo311908ga** [comment]
but i did

**Comment by ComputerElite** [comment]
If it says you do not own the game then you did not log in with the **correct** meta account

**Comment by Rodrigo311908ga** [comment]
ohhhhhhh
