### ISSUE TITLE
Update QAVS and Storage Perms Popup Stops Game Modding Process

### ISSUE THREAD

**Issue by hdgamer1404Jonas** [ComputerElite/QuestAppVersionSwitcher#38]
When trying to mod a Game (BeatSaber) the Update QAVS and Storage perm Popup randomly Pops up half way through the modding Process which makes it start from the beginning

**Comment by ComputerElite** [comment]
Could you give more details about when it pops up

**Comment by hdgamer1404Jonas** [comment]
It only seems to pop up if youre running an outdated version of QAVS. When it promps you to uninstall beatsaber, instead of uninstalling the app, it opens the popup which asks you if you want to update QAVS

**Comment by ComputerElite** [comment]
Well then, why are you running an outdated version and don't update when it asks you to?

**Comment by hdgamer1404Jonas** [comment]
I did eventually update, i just thought it could be infuriating to other users who just want to mod the game

**Comment by ComputerElite** [comment]
When the update prompt comes up you update. Period.

**Comment by AltyFox** [comment]
I'm with Jonas on this one.   Not everyone wants to do that right away and just want to play the game.
I would consider this a UX issue.   The update prompt shouldn't reappear if it's been dismissed.
