### ISSUE TITLE
Crashing upon opening

### ISSUE THREAD

**Issue by nintendoGame10** [ComputerElite/QuestAppVersionSwitcher#39]
Not me, but my friends modded beat saber crashes upon opening. Any ideas on how to fix it?

**Comment by ComputerElite** [comment]
That's not related to QuestAppVersionSwitcher. You can seek for help on the BSMG discord server at https://discord.gg/beatsabermods

**Comment by nintendoGame10** [comment]
He modded it using QAVS, how is that not related

**Comment by kodenamekrak** [comment]
The specific mods added are causing it to crash, not QAVS itself, so QAVS is not responsible for the crashes
