### ISSUE TITLE
Downgrade database page will never load on Quest 1

### ISSUE THREAD

**Issue by Kokorone** [ComputerElite/QuestAppVersionSwitcher#41]
On Quest 1, the downgrade database page will never load making it impossible to select a version to downgrade

**Comment by ComputerElite** [comment]
Could you give more infos on what exactly you're seeing? Just loading animation?

**Comment by Kokorone** [comment]
Yep, it’ll reach the QuestDB page then sit there with 6 or so loading circles. I’ve tested on a quest 2 and it loads instantly. Quest 1 has some kind of bug.

**Comment by ComputerElite** [comment]
If you got a pc could you contact me on Discord rq to get this sorted?

my username is computerelite

**Comment by ComputerElite** [comment]
Fixed
