### ISSUE TITLE
Quest 3 Support

### ISSUE THREAD

**Issue by Omay238** [ComputerElite/QuestAppVersionSwitcher#43]
I believe this is on your radar, although I thought it would be good to have here.

**Comment by AltyFox** [comment]
QAVS already *has* Q3 support primed and ready to go.  The issue isn't QAVS or even BMBF for that matter.  The issue is the modloader for BeatSaber, and it's being worked on.

**Comment by AltyFox** [comment]
But for simple app managment, QAVS already works.

**Comment by Omay238** [comment]
Installing dev build seemed to fix QAVS. I guess the version currently available on SideQuest still doesn't work on Quest 3

**Comment by ComputerElite** [comment]
Yeah, still waiting on a few people to confirm everything works in the dev build cause under the hood a few bigger changes were made (which in part don't even have to do with Q3)
