### ISSUE TITLE
switch to different app

### ISSUE THREAD

**Issue by Spudhead** [ComputerElite/QuestAppVersionSwitcher#45]
i used this for beatsaber but now i need to downgrade a different app. when i open appswitcher it always goes to beatsaber. i tried the back arrow at the top right and it goes back but just spins forever. how can i downgrade something other than beatsaber?

**Comment by ComputerElite** [comment]
Which app are you trying to downgrade?

**Comment by ComputerElite** [comment]
Apps that are not often downgraded take longer to load, especially if they have a lot of versions

**Comment by Spudhead** [comment]
Puzzling places. Does it matter? I can’t get far enough to do anything. It just shows the spiny thing.

On Nov 13, 2023, at 3:36 PM, ComputerElite ***@***.***> wrote:

﻿

Which app are you trying to downgrade?

**Comment by hdgamer1404Jonas** [comment]
You switch the app by going to the "Tools & Options" tab and clicking the change App button. Clicking the back button at the top just brings you to the leading screen.

**Comment by ComputerElite** [comment]
Seems to load for me, press the upload logs button in tools and options and post the id it tells you here please

**Comment by Spudhead** [comment]
Thank you that pointed me in the right direction, I got the list of installed apps, but then nothing happens when I click on any of them. I tried in the headset and through the web interface on pc… what (probably really obvious thing) am I missing?

Thx again.

On Nov 13, 2023, at 8:38 PM, Jonas W ***@***.***> wrote:

﻿

You switch the app by going to the "Tools & Options" tab and clicking the change App button. Clicking the back button at the top just brings you to the leading screen.

**Comment by ComputerElite** [comment]
> press the upload logs button in tools and options and post the id it tells you here please
Could you do that please?

**Comment by Spudhead** [comment]
ID: F161A4

**Comment by ComputerElite** [comment]
I can't find any indication of an issue in that log. Could you just try again? if it doesn't work record a video and post it here or (if prefered) dm me on Discord ˋcomputereliteˋ

**Comment by Spudhead** [comment]
I did manage to fix it. I had to log out then back in again and it worked. A few days later the same behavior happened again and the the same fix worked.

Thx for the help.

On Nov 27, 2023, at 4:17 PM, ComputerElite ***@***.***> wrote:

﻿

I can't find any indication of an issue in that log. Could you just try again? if it doesn't work record a video and post it here or (if prefered) dm me on Discord ˋcomputereliteˋ
