### ISSUE TITLE
Meta login error

### ISSUE THREAD

**Issue by Mastergaming1x** [ComputerElite/QuestAppVersionSwitcher#46]
When I login to my meta account, it would bring me to the meta website but it would just keep refreshing and won't stop.

**Comment by ComputerElite** [comment]
Restart your quest and try again

**Comment by Mastergaming1x** [comment]
> Restart your quest and try again

Thanks for the reply but I have already tried that multiple times.

**Comment by ComputerElite** [comment]
Could you press upload logs in tools and options and share the id it gives you here?

**Comment by Mastergaming1x** [comment]
> Could you press upload logs in tools and options and share the id it gives you here?

As soon as I was about to, the problem was fixed for some reason but I'm glad though. I guess everything is fine for now so thanks for your help.
