### ISSUE TITLE
"This is ToDo"

### ISSUE THREAD

**Issue by MaxBro468** [ComputerElite/QuestAppVersionSwitcher#47]
When I go to "Downgrade", it says "This is ToDo". I tried getting an old version of the app, but when I tried downgrading, it says that the account logged in "doesn't own the app I'm trying to downgrade". How do I fix this?

**Comment by AltyFox** [comment]
You don't.  Meta broke things. That's why the latest release says Todo.

**Comment by ComputerElite** [comment]
Downgrade tab was updated to show current possibilities of downgrading in 1.15.3 just now
