### ISSUE TITLE
Apk download stuck on 0% 

### ISSUE THREAD

**Issue by ExqueeseMe** [ComputerElite/QuestAppVersionSwitcher#48]
Beat Saber apk downloads get stuck on 0% and after some time says "an unknown error occured"

**Comment by ComputerElite** [comment]
Could you got into tools and options (or the help button depending on what you see) and press upload logs? Then post the id here

**Comment by ExqueeseMe** [comment]
Alright I pressed it.

**Comment by ComputerElite** [comment]
Please share the id you were given here

**Comment by ExqueeseMe** [comment]
Its been loading for a long time so idk if its my headset or the app

**Comment by ComputerElite** [comment]
Just restart your quest and try again

**Comment by ExqueeseMe** [comment]
1C31B3 is my log number, i factory reset my quest but still get the same issue

**Comment by ComputerElite** [comment]
Well you're not logged in with your account

**Comment by ExqueeseMe** [comment]
thats weird because it says i am? It accepted my token

**Comment by ExqueeseMe** [comment]
and when i do type my token it tells me it needs to start with fra. Even though my token doesn't start with fra

**Comment by ExqueeseMe** [comment]
I can't log in normally because I have the infinite loading if i try to login the other way.

**Comment by ComputerElite** [comment]
> and when i do type my token it tells me it needs to start with fra. Even though my token doesn't start with fra

The login with token button isn't updated yet with the new token type

> I can't log in normally because I have the infinite loading if i try to login the other way.

Could you make a video of the issue?

**Comment by ComputerElite** [comment]
> > and when i do type my token it tells me it needs to start with fra. Even though my token doesn't start with fra
> 
It will work if you try it on the latest version
> 
> > I can't log in normally because I have the infinite loading if i try to login the other way.
> 
> Could you make a video of the issue?

**Comment by ComputerElite** [comment]
Sure

**Comment by ExqueeseMe** [comment]
![56](https://github.com/ComputerElite/QuestAppVersionSwitcher/assets/155256224/b9aa1c7d-8e7f-485f-b381-4a1706903889)
gets stuck on this forever

**Comment by ComputerElite** [comment]
Could you upload your logs from the tools and options tab and share the id you get?

**Comment by ExqueeseMe** [comment]
I think it looks like the logs also has the infinite loading. It's stuck on "collecting information" and it's been like WAAY more than 40 seconds.

**Comment by ComputerElite** [comment]
Seems like an issue with your Internet connection then

**Comment by ExqueeseMe** [comment]
i think it might be my firewall blocking it

**Comment by ComputerElite** [comment]
Probably, nothing I can do there sadly. Perhaps you can try a vpm

**Comment by ExqueeseMe** [comment]
I'll just login with my token, thanks for the help.
