### ISSUE TITLE
Unable to log in to Facebook through the app.

### ISSUE THREAD

**Issue by jconner1a** [ComputerElite/QuestAppVersionSwitcher#5]
Hello!  I'm currently trying to downgrade Beat Saber with this app.  Every time I try to login to my Facebook through it, a pop up appears that says something like "You have to restart QuestAppVersionSwitcher in to finish logging in."  When I click the "Close app" button and then reopen the app, it gives me the same prompt to login to Facebook.  I try to log in and the same pop up from earlier appears.  This just keeps happening on a loop.  Any advice on this?  Thank you!

**Comment by ComputerElite** [comment]
Try restarting your quest

**Comment by jconner1a** [comment]
@ComputerElite 

Same results ;/

**Comment by ComputerElite** [comment]
As I as well as my other testers don't get that issue I can't really help you. However you could try resetting your app data with sidequestm

**Comment by Oli567856** [comment]
I got the exact same issue right now, stuck in an endless loop, redownloading and restarting does nothing

**Comment by ComputerElite** [comment]
Would anyone of you mind to go on a call with discord so we can screenshare? Send a friend request to ComputerElite#0486

**Comment by Sossij** [comment]
Has this been solved? I just downloaded last night and am having this same issue.

**Comment by ComputerElite** [comment]
Nope it hasn't. Do you have time to hop on a discord call?

**Comment by Sossij** [comment]
Just about to head to work, but tonight I can

**Comment by ComputerElite** [comment]
Send me a friend request when you have time ComputerElite#0486

**Comment by ComputerElite** [comment]
This issue has been resolved by adding back the login via token method
