### ISSUE TITLE
downloading does not create a backup

### ISSUE THREAD

**Issue by SilvazWasTaken** [ComputerElite/QuestAppVersionSwitcher#50]
you can go onto the backups tab and create one. that works fine. however, when you download a version (i am logged in fine) on quest OR pc it doesnt create a backup and instead creates a seperate game with the backup name?? you also cant click download it just skips from step 1 to step 2.4 and says u did it. im on quest 2 this is so annoying

**Comment by ComputerElite** [comment]
QAVS creates a backup when you download an old version. That's how it keeps track of everything. The backup is stored for the app you downloaded. E. G. If you download rec room you'll have to press change app and slect com.AgainstGravity.RecRoom

**Comment by ComputerElite** [comment]
Which game were you downloading?

**Comment by ComputerElite** [comment]
After reviewing it it seems like I sneaked a bug into the last update while changing some download code. Apologies. I'll take a look at it and publish a fix

**Comment by ComputerElite** [comment]
Okay, I tracked the issue down to not QAVS but OculusDB. It fails to correctly specify the package name for apps

**Comment by SilvazWasTaken** [comment]
i was trying to download an old ver of gorilla tag, just any old ver doesnt work

**Comment by ComputerElite** [comment]
That should be working again

**Comment by SilvazWasTaken** [comment]
thanks
