### ISSUE TITLE
Features manifest patching feature does not seem to work

### ISSUE THREAD

**Issue by FrozenAlex** [ComputerElite/QuestAppVersionSwitcher#52]
I added passthrough to features in the patching section with sl2 and it did not appear in the final manifest. Changing the manifest might be somehow broken

**Comment by ComputerElite** [comment]
I indeed literally do nothing with the requested features in the patching code

**Comment by ComputerElite** [comment]
Try this build please https://github.com/ComputerElite/QuestAppVersionSwitcher/releases/tag/1.15.14

**Comment by ComputerElite** [comment]
Well Alex, you haven'T tested so this is considered as completed
