### ISSUE TITLE
OculusDB downgrade feature removed - Diff patching only

### ISSUE THREAD

**Issue by petermg** [ComputerElite/QuestAppVersionSwitcher#53]
Was the search feature removed from Downgrade? Two versions ago I was able to manually search for an app, but now it seems to only allow me to select an app that's currently installed. I was using this for some older Go/GearVR apks to download so I switched back to an older version (15.14), unless I'm doing something wrong?

**Comment by ComputerElite** [comment]
Oculus broke the feature. Until I find a workaround you cannot simply download any version of any app

**Comment by ComputerElite** [comment]
It was indeed disabled and replaced with a way worse version which just works for beat saber to some versions

**Comment by petermg** [comment]
Oh no! Really? It was working for me just a few days ago! Was this very
recent? If so, I'm glad I downloaded what I was looking for then!

**Comment by petermg** [comment]
> Was just this morning. About 12 hours ago

Oh man, first they did it to DownQuest... now yours too!!! Maybe they will switch it back? I hope so. Or hows about this, is there a way you can spoof a headset ID and make Oculus think it's a request from the actual account AND headset the game is intended for? For example GearVR apps it will mimic a GearVR device ID or something like that? Should work right? I mean unless GearVR users cannot download software they paid for anymore?

**Comment by ComputerElite** [comment]
Not how it works. You need an access token. At first you could simply use one from the oculus store website. Then the oculus pc app ui and now it has to be one from the oculus runtime or ocmd (oculus core mobile services).  It's harder to figure out how to generate those tokens.

**Comment by petermg** [comment]
Does the PC VR version of the downgrader still work then, or no?

**Comment by ComputerElite** [comment]
Nope, they work the same way

**Comment by petermg** [comment]
> Not how it works. You need an access token. At first you could simply use one from the oculus store website. Then the oculus pc app ui and now it has to be one from the oculus runtime or ocmd (oculus core mobile services). It's harder to figure out how to generate those tokens.

Is it possibly to run them in a virtual environment to get the tokens? Or something like that?

**Comment by ComputerElite** [comment]
I mean yeah. But it won't tell you how to get tokens. I can't just run the entire virtualized quest os in QAVS just to get a token

**Comment by petermg** [comment]
> I mean yeah. But it won't tell you how to get tokens. I can't just run the entire virtualized quest os in QAVS just to get a token

So I've been thinking. I've got a Oculus Go and they have an unlocked bootloader firmware for it. From what I've read, it's not too hard to root once the bootloader is unlocked. If I do that maybe you can give me suggestions on helping you figure out how to get that token?

**Comment by ComputerElite** [comment]
Update on this: Downloading Go and GearVR games works with QAVS and other downgrading tools no problem. Just quest is the problem so the go isn't any help sadly

**Comment by petermg** [comment]
> Update on this: Downloading Go and GearVR games works with QAVS and other downgrading tools no problem. Just quest is the problem so the go isn't any help sadly

Then how do I download the Go and GearVR games that I've purchased? Please advise.

**Comment by ComputerElite** [comment]
Just use Oculus Downgrader

**Comment by petermg** [comment]
Trying to download a couple GearVR apps. I have it set to GearVR for the
headset and I keep getting the following error:

Starting download of 1502317809794114
Downloading
https://securecdn.oculus.com/binaries/download/?id=1502317809794114&access_token=
  ██████████████████████████████ 0 / 0   Download started
  ██████████████████████████████ 0 Bytes / 0 Bytes   An error occured

Error while downloading
Download failed


Check if you got the right headset selected (option 8). Rift for Oculus
Link, Air link and Rift/Rift s. Quest for Quest 1 and 2

**Comment by ComputerElite** [comment]
Make sure you own the game you try to download

**Comment by ComputerElite** [comment]
However it seems to me as if you clicked on the rift/quest version

**Comment by ComputerElite** [comment]
Change the headset to gearvr with option 8

**Comment by petermg** [comment]
> Make sure you own the game you try to download



> However it seems to me as if you clicked on the rift/quest version

I do own them and according to the app I have it set to GearVR.:

Starting download of 25321068390842250
Downloading https://securecdn.oculus.com/binaries/download/?id=25321068390842250&access_token=
  ██████████████████████████████ 0 / 0   Download started
  ██████████████████████████████ 0 Bytes / 0 Bytes   An error occured

Error while downloading
Download failed


Check if you got the right headset selected (option 8). Rift for Oculus Link, Air link and Rift/Rift s. Quest for Quest 1 and 2

[1]  Downgrade Beat Saber (Not available on GearVR)
[2]  Downgrade another GearVR app
[3]  Install App
[4]  Open app installation directory (ONLY do if you know what you are doing. If you want to start the app, use option 3)
[5]  Update access_token
[6]  Update oculus folder
[7]  Validate installed app
[8]  Change Headset (currently GearVR)
[9]  Install Package
[10] Create Backup
[11] Direct execute
[12] Open graphical ui
[13] Settings
[14] Exit

**Comment by ComputerElite** [comment]
Once again that's the quest app.

**Comment by ComputerElite** [comment]
Try this with option 11 `https://oculusdb.rui2015.me/id/25321068390842250`

**Comment by ComputerElite** [comment]
wait
meant this
d --appid 908477449239883 --versionid 940886972650646 --headset GEARVR

**Comment by petermg** [comment]
> Try this with option 11 `https://oculusdb.rui2015.me/id/25321068390842250`

I get:

Enter the code or a file path: https://oculusdb.rui2015.me/id/25321068390842250
Parsing -nU --userexecuted https://oculusdb.rui2015.me/id/25321068390842250


Check if you got the right headset selected (option 8). Rift for Oculus Link, Air link and Rift/Rift s. Quest for Quest 1 and 2

**Comment by petermg** [comment]
> d --appid 908477449239883 --versionid 940886972650646 --headset GEARVR

I get this:

Choice: 11
Enter the code or a file path: d --appid 908477449239883 --versionid 940886972650646 --headset GEARVR
Parsing -nU --userexecuted d --appid 908477449239883 --versionid 940886972650646 --headset GEARVR
Set headset to GearVR

  / Requesting version from Oculus due to version id existing

Version: 1.3.3 (940886972650646)
Changelog: Initial Version

Starting download
Saving version info

Starting download of 940886972650646
Downloading https://securecdn.oculus.com/binaries/download/?id=940886972650646&access_token=
  ██████████████████████████████ 0 / 0   Download started
  ██████████████████████████████ 0 Bytes / 0 Bytes   An error occured

Error while downloading
Download failed


Check if you got the right headset selected (option 8). Rift for Oculus Link, Air link and Rift/Rift s. Quest for Quest 1 and 2

**Comment by ComputerElite** [comment]
Send the `log.log` file please

**Comment by petermg** [comment]
> Send the `log.log` file please

[Log.log](https://github.com/ComputerElite/QuestAppVersionSwitcher/files/15049636/Log.log)
Ok here you go.

**Comment by ComputerElite** [comment]
hm interesting

**Comment by ComputerElite** [comment]
I can confirm that it also doesn't work anymore for me. Just the other day I was able to download some go game however

**Comment by petermg** [comment]
> I can confirm that it also doesn't work anymore for me. Just the other day I was able to download some go game however

Darn Meta... :(

**Comment by ComputerElite** [comment]
Downgrading works again

**Comment by petermg** [comment]
> Downgrading works again

SWEEEEEEEEEET!!!!!! Gonna try this now!
