### ISSUE TITLE
QAVS getting stuck on Diff Patching

### ISSUE THREAD

**Issue by hdgamer1404Jonas** [ComputerElite/QuestAppVersionSwitcher#55]
QAVS seems to get stuck on 99% when diff patching for some people. It does nothing after, etc. When waiting for a few minutes after it gets stuck the downgraded version still appears in backups.

**Comment by ComputerElite** [comment]
QAVS indeed does not broadcast the download done event so the ui doesn't know it's done. Will be fixed in the next version

**Comment by ComputerElite** [comment]
For context: QAVS has a websocket it can subscribe to which only sends what changes and api endpoints it can pull info from which gets everything with correct status. On the backend I have to send what changes cause the ui only uses the websocket (until it doesn't). For downloads it does and I forgot to send it on diff applied

**Comment by ComputerElite** [comment]
interesting

**Comment by ComputerElite** [comment]
Didn't know commits could close issues
