### ISSUE TITLE
Obb disappeared -Need Help

### ISSUE THREAD

**Issue by KSHAN03** [ComputerElite/QuestAppVersionSwitcher#59]
I am soooo out of my element. I was just trying to delete a broken mod from QAVS through SideQuest, which I still wasn't able to do, but now when I click to open QAVS and do the allow access and use this folder thing, it says something along the lines of "this file isn't available to be used, please choose another file for your safety". Usually I just do 3 simple clicks, allow access, use this folder, use this folder, and I'm through. Now it's not doing that AND I still have a broken mod on Beat Saber. HELP PLEASE

**Comment by ComputerElite** [comment]
Meta did a software update which introduced this bug. You cannot manage your mods with QAVS while this bug in the OS persists. You must use [QuestPatcher](https://github.com/Lauriethefish/QuestPatcher/releases/latest) to install and manage mods at the moment

**Comment by KSHAN03** [comment]
Ughhh gotcha. Any idea on how to get QAVS back to normal so it has the access/data/obb thing back? Or is it missing the specific glitch going on? Or is it the mods not being able to be deleted? Or both?

**Comment by ComputerElite** [comment]
As said Meta is at fault. Until they fix their OS you cannot use QAVS for installing mods and must instead use quest patcher

**Comment by KSHAN03** [comment]
Ohhhh I didn’t realize there were more mod programs 😅 thank you! I just finished going through the quest patcher steps. I know this isn’t really related here, but is there a backup function there like QAVS? I’m a paranoid backer-upper, but I don’t see a tab like there is on QAVS.

**Comment by ComputerElite** [comment]
Nope, QuestPatcher doesn't support backups

**Comment by ComputerElite** [comment]
Update on this. The latest QAVS version now supports modding on standalone again. Have fun!
