### ISSUE TITLE
Allow rooting for standalone

### ISSUE THREAD

**Issue by SomeOriginalCreator** [ComputerElite/QuestAppVersionSwitcher#68]
Maybe you could allow rooting like ZArchiver so you can access obb/data folders on standalone using shizuku.
![com oculus shellenv-20240626-151324](https://github.com/ComputerElite/QuestAppVersionSwitcher/assets/102445176/55265c0c-a7e0-4a7d-be73-14445c178beb)

**Comment by ComputerElite** [comment]
We have experimented with this and successfully implemented an adb client which could execute commands. However the thing is that you're required to pair with the quest by entering a port and code or use a pc. If you want to help implement that hit me up on discord. I haven't had motivation to do this. discord: computerelite

**Comment by ComputerElite** [comment]
Due to findings on downgrading I've gained motivation to work on this again and it's currently working on a Pixel 6. Testing on quest will be done later

**Comment by ComputerElite** [comment]
The latest release allows you to do exactly that.
