### ISSUE TITLE
converting beat saber to older version

### ISSUE THREAD

**Issue by daboizz** [ComputerElite/QuestAppVersionSwitcher#7]
when i use the app to convert beat saber to 1.24.0 it comes up with an error while it downloads saying i havent logged in with a key or i dont own the app but i logged in with a key and i have beat saber

**Comment by ComputerElite** [comment]
Make sure you logged in with the right account. That's usually the issue. If you are 100% sure use the login button in the tools and options tab and if that doesn't work get a token

**Comment by daboizz** [comment]
i did what u said and none of the options worked, i checked i got the right account, i logged in with the token and it still didnt work, what should i do

**Comment by ComputerElite** [comment]
Did you validate your token on the token guide? The validity checker is near the bottom

**Comment by daboizz** [comment]
yeah

**Comment by ComputerElite** [comment]
well then you simply don't own beat saber

**Comment by ComputerElite** [comment]
then you logged into the wrong account. You have to log into the account you own beat saber on

**Comment by daboizz** [comment]
ive only had 1 meta account and i got the token from there

**Comment by daboizz** [comment]
![Oculus Store_ VR Games, Apps and More _ Oculus - Opera 08_09_2022 17_50_43](https://user-images.githubusercontent.com/113128230/189180355-7d1c786c-8468-43e0-8bc4-c8bee8cab4c0.png)

**Comment by ComputerElite** [comment]
can you send a screenshot of the token validator (DONT include the token itself)

**Comment by daboizz** [comment]
![Oculus Store_ VR Games, Apps and More _ Oculus - Opera 08_09_2022 17_52_52](https://user-images.githubusercontent.com/113128230/189180724-b7639a48-601e-4865-a7b6-d68b10c411d7.png)

**Comment by ComputerElite** [comment]
have you tried restarting your quest yet?

**Comment by daboizz** [comment]
alright ill try that

**Comment by daboizz** [comment]
yeah it worked thank you

**Comment by ComputerElite** [comment]
no problem
