### ISSUE TITLE
QuestAppVersionSwitcher not working anymore

### ISSUE THREAD

**Issue by Nibiru-1** [ComputerElite/QuestAppVersionSwitcher#70]
Hi, i was looking into the app switcher to see if there's a mod to control the camera, because when i record my play on beat saber and it shows that i'm looking down, but i'm not. When i got to the app switcher, it asked for an up date, so i updated it.  i go click on it to open it, i doesn't open anymore.  i rebooted my headset, i tried to reinstall it and failed to install.

**Comment by ComputerElite** [comment]
Could you provide a logcat:

1. Download the latest version of [QuestPatcher](https://github.com/Lauriethefish/QuestPatcher/releases/latest) for your platform.
 - __**NOTE:**__ If you are on MacOS, the first time opening the program, you will have to `Left Click -> Open -> Open`.
2. Plug your Quest into your computer.
3. Click the `Start ADB Log` button inside the `Tools & Options` tab.
4. Open the game and reproduce the crash or the issue you are facing, then press `Stop ADB Log`.
5. Press `Open Logs Folder`, and upload the `adb.log` file here

**Comment by ComputerElite** [comment]
install 1.16.2 that fixed it

**Comment by Nibiru-1** [comment]
I haven’t had time to do this but will soon. I’m just scared that I’ll have to remod and I would unable to remod again

Michelle

On Aug 11, 2024, at 5:14 PM, ComputerElite ***@***.***> wrote:

﻿

install 1.16.2 that fixed it

**Comment by phaze-the-dumb** [comment]
I've just unsubscribed you from this thread, sorry about that.

**Comment by Nibiru-1** [comment]
That’s ok. As of yesterday thanks to my daughter. I don’t need QuestAppSwitcher. I unlocked all the mods, sabers and everything with a pc. All good. Thank   I was too scared that I had no choice but to remod and it’s that file that stops me from remod and it’s scotland2
Michelle

On Sep 1, 2024, at 12:25 PM, Phaze ***@***.***> wrote:

﻿

I've just unsubscribed you from this thread, sorry about that.

**Comment by ComputerElite** [comment]
Yeah, great to hear. QAVS does have small issues I've been slowly fixing. A windows update kinda messed with my development environment this development has been slower. In case you do try QAVS again feel free to report back. It should be able to install and update mods as well as manage sabers and so on

**Comment by Nibiru-1** [comment]
Ok cool. I will. Thanks
Michelle

On Sep 2, 2024, at 2:57 PM, ComputerElite ***@***.***> wrote:

﻿

Yeah, great to hear. QAVS does have small issues I've been slowly fixing. A windows update kinda messed with my development environment this development has been slower. In case you do try QAVS again feel free to report back. It should be able to install and update mods as well as manage sabers and so on
