### ISSUE TITLE
The new use of Lightning Launcher seems to be bugging my modding

### ISSUE THREAD

**Issue by Fura-x** [ComputerElite/QuestAppVersionSwitcher#74]
Hi, I'm on Quest 2, I was using QuestAppVersionSwitcher at the beggining of the year and it was working properly.
Then when Beat Saber released OST 7 I go back to the restored version.

Now I want to mod my game again (without PC), but the latest update ask me for download Lightning Launcher so that I can pair the adb stuff and, well, I'm not an expert, but it worked.

I mean, i succeeded to follow the tutorial and all, but when I restore a backup or just re-downgrade my Beat Saber file, then patched it, then download all the mods... Well, my Beat Saber isn't modded at all.

When I launch it from the Quest 2 Launcher, the app is just downgrade, even if the QuestAppVersionSwitcher's mod tap shows all the mod I installed. 

When I launch it from the Lightning Launcher, Beat Saber just appears in a scaled window next to the Lightning Launcher window, and I can't interact with it... Since it scaled, I can't even see if there are mods or not.

That's all, sorry for this very long monologue, with no capture. This is to begin with, in case the solution is simple. But of course I can bring screenshots or debug log with my PC if you explain how...

I think the issue is similar to this one closed 3 days ago, but the bug come further in the process, I hope it is okay.

**Comment by ComputerElite** [comment]
QAVS currently has some issues with installing mods. It might've modded your game incorrectly. Please go into QAVS -> Tools & Options -> Upload log and share the code here

**Comment by Fura-x** [comment]
code is E1C38

**Comment by Fura-x** [comment]
I just tried to uninstall and re-install QAVS and LL, and I came back to the same issue, except that each time I close and open QAVS, the QAVS Assistant window opens as if it was the first time. However, I just clicked on "next" and QAVS realized that I already mapped the game so it's okay. But I have to toggle on all my mods each time, even if it won't change the original issue, maybe this has something to do with this...

**Comment by Fura-x** [comment]
The log I share is after all this

**Comment by Fura-x** [comment]
Should I retry to mod my Beat Saber or wait for the next QAVS update?

**Comment by ComputerElite** [comment]
Oh sorry, I forgot about this. I'll take a look at it this afternoon

**Comment by ComputerElite** [comment]
Perhaps if you have time you could share a video of  what the modding process is like for you?

**Comment by ComputerElite** [comment]
If not that's also not a problem

**Comment by Fura-x** [comment]
> Perhaps if you have time you could share a video of what the modding process is like for you?

I'll do this when I have the time to, maybe not today though

**Comment by ComputerElite** [comment]
Okay, I found the reason why you're experiencing this problem

**Comment by Fura-x** [comment]
Great, should I follow specifics steps or wait for a code update ? Thank you so much for your work 🙏

**Comment by ComputerElite** [comment]
I might be able to get a update out in 40 mins. You'll have to manually install it tho and can then report back if it helped or not

**Comment by ComputerElite** [comment]
I'll send a message here with further instructions later

**Comment by ComputerElite** [comment]
Sorry for the wait, You can download a zip file which contains an apk here https://github.com/ComputerElite/QuestAppVersionSwitcher/actions/runs/10937762096

Install it to your quest with SideQuest or adb or something similar and then try to mod your game again. I did not test it but hope it fixes most of the stuff. Upload a log once you're done and lmk how it goes please

**Comment by Fura-x** [comment]
Hi, sorry but it doesn't work, I reinstalled everything from the beginning with the apk you gave me but nothing changed in the end, I have a downgraded Beat Saber without mods :((

I upload logs, code is : 23331C

I didn't record a video of the installation process, but here is a video of my QAVS setup

https://github.com/user-attachments/assets/6740e157-8c7d-4720-9746-e691cdef9bfd

**Comment by ComputerElite** [comment]
Sorry once again for the late response. I think I've found the issue there. Could you do the same steps as before with this build? https://github.com/ComputerElite/QuestAppVersionSwitcher/actions/runs/11007775399

**Comment by Fura-x** [comment]
OMG it worked! My Beat Saber is modded, and I got back all my songs :))

Here is the log upload code : CA8391

And also if you want I recorded all my download process, if you want I can upload the video on Google Drive or whatever.

Thank you so much !!

**Comment by ComputerElite** [comment]
Amazing! I would appreciate a video as well

**Comment by ComputerElite** [comment]
Also fyi. When the new QAVS update releases publicly (or at least at the next one when QAVS prompts you) you will have to manually update by uninstalling QAVS as the signature between action builds and the builds I publish in the releases difffer.

**Comment by Fura-x** [comment]
Hello !

First, here is a link to my modding process video :
https://drive.google.com/file/d/1uioeWfc4etDGq_HvrzrB0JaruNGZHIJz/view?usp=sharing
I sped up the download part, but I kept everything

Also, I have an issue with optional mods, I can download them, but they're not in the game. It's not important, though.
https://github.com/user-attachments/assets/c4393540-958e-499b-a119-4ad552a38fe9

**Comment by ComputerElite** [comment]
Iirc optional mods are mods that a mod supports but does not need. They're not downloaded automatically

**Comment by ComputerElite** [comment]
That's the same behavior quest patcher has and thus I just copied that

**Comment by ComputerElite** [comment]
Thanks for that video. QAVS still seems to be hella broken so I'll see what I can do. Thanks for your time!
