### ISSUE TITLE
App breaks on Quest 3 if I install update 1.16.8

### ISSUE THREAD

**Issue by SarakayaKomzin** [ComputerElite/QuestAppVersionSwitcher#78]
1. Install app on Quest 3 via Sidequest, on device or by connected computer. 
2. Open app on Quest 3
3. It immediately asks me if I'd like to install the newest update. If I click yes, I go through the update flow, and nothing in the app is clickable ever, even after a restart or after turning on the permission in Settings. If I click no and do not install the update, the app works normally but does hassle me about installing the update.

**Comment by ComputerElite** [comment]
Whoops, just pushed an update which should fix that. lmk if that fixes it for you. Wasn't able to test it

**Comment by ComputerElite** [comment]
App was tested by other persons, it seems to work now. If any issue rises, feel free to reopen this issue
