### ISSUE TITLE
Uninstall Beat Saber

### ISSUE THREAD

**Issue by Cliff75** [ComputerElite/QuestAppVersionSwitcher#8]
After uninstalling Beat Saber successfully it continues with trying to install the downgraded apk file.  It goes to about 75% and then stops working.  Next prompt checks to see if it's installed and it's not.  So it's stuck in a loop of trying to install it.

**Comment by ComputerElite** [comment]
Disable app sharing and multiple accounts

**Comment by Cliff75** [comment]
Yep, that's it.  I had to uninstall it from one of the shared accounts.  Thanks
