### ISSUE TITLE
Flow now has an invalid URL for installing qmod.  Should just cause QAVS to silently fail

### ISSUE THREAD

**Issue by AltyFox** [ComputerElite/QuestAppVersionSwitcher#80]
User will still have to manually install the core mods from the get mods page.
This is a regression.
The new mods repo doesn't have a ready made core mods .qmod file for download.
As the mod site is built, this would not be an easy fix on the mod site, since the QMOD is generated in Javascript on the fly.
Suggested options would be:
1. Create a new `?isflow=true|false` flag that makes the user click the core mods button *first* on the mods site.
2. Use the known core_mods json and implement the same QMOD generation technique (Not a fan of this, as its code replication, and would require two changes instead of one if something changed down the line)
3. Update `QAVSModManager.InstallModFromUrl()` to detect the .json file and iterate through the core mods for the currently installed version and add them to the queue.
4. Ignore it, and let the end-user make mistakes

**Comment by ComputerElite** [comment]
I'd say it's not hard to add core mods to the mods repo as it runs a action periodically anyways

**Comment by DanTheMan827** [comment]
Couple options.

- The core mods repo could have a qmod generation action added, in fact this already has had a PR for some time https://github.com/QuestPackageManager/bs-coremods/pull/4
- BSQMods could automatically download the core mods in response to a query string parameter
- BSQMods could include an action to periodically generate a cores qmod

**Comment by ComputerElite** [comment]
Oh, I thought the mods repo would mirror the core repo. In that case an action on the core repo would be best

**Comment by DanTheMan827** [comment]
The mods repo does contain all of the core mods, but also potentially newer versions scraped in an auto-update as well.  The core mods repo tends to lag behind the mods repo because it's manually updated.

I guess they want to make sure it's fully stable before adding it to the coremods repo.

**Comment by AltyFox** [comment]
Sounds to me like still having the qmod be generated might be the easiest course of action.  a simple check to the action to make sure it aligns with the core mods, and if not create it and publish it.
