### ISSUE TITLE
QAVS keeps crashing

### ISSUE THREAD

**Issue by AndromedaTM** [ComputerElite/QuestAppVersionSwitcher#90]
I've noticed since the 19th that QAVS keeps crashing whenever i open the app (i'm on quest 2, latest version, v72 if that helps any)

**Comment by ComputerElite** [comment]
Please upload your log via the tools and options tab then share the code you get here

**Comment by AndromedaTM** [comment]
How do i do that?

**Comment by AndromedaTM** [comment]
Nevermind, I was able to mod beat saber using ModsBeforeFriday
